### ISSUE TITLE
token_info.expire_time is required 

### ISSUE THREAD

**Issue by yangeee** [aliyun/aliyun-pds-js-sdk#1]
旧版本0.0.1已经跑通上线，更换了最新版之后出现了这个问题

1、已经添加了这个字段，仍然会出现这个字段缺少的报错
![image](https://user-images.githubusercontent.com/23137277/154180362-7fd4ce3f-4112-4392-959d-a47504e8cc75.png)
![image](https://user-images.githubusercontent.com/23137277/154180392-aabaa9d7-6113-4144-bd38-1a09f2c644a2.png)

2、expire_time字段应该不是必需的，旧版本不用传，官网文档也是不用的
![image](https://user-images.githubusercontent.com/23137277/154180538-b3505cf4-c4b7-4efb-90e4-5f8a842ed988.png)

**Comment by aleelock** [comment]
token_info 最好直接传入所有字段。用JWT生成的token或者OAuth登录获取的token，都是一个完整的 token_info JSON格式。
expire_time 的格式应该是能通过 Date.parse(expire_time) 的格式，比如："2022-02-16T07:59:14Z"。

**Comment by yangeee** [comment]
> token_info 最好直接传入所有字段。用JWT生成的token或者OAuth登录获取的token，都是一个完整的 token_info JSON格式。 expire_time 的格式应该是能通过 Date.parse(expire_time) 的格式，比如："2022-02-16T07:59:14Z"。

感谢您的回复，问题已解决
