### ISSUE TITLE
FilePutUserTags - 添加文件自定义标签是否支持？

### ISSUE THREAD

**Issue by underweather** [aliyun/aliyun-pds-js-sdk#6]
您好，请问下FilePutUserTags - 添加文件自定义标签这个方法在js-sdk是否实现？如果没有，想实现类似的功能，目前可以调用那个api呢？谢谢

**Comment by aleelock** [comment]
目前还没有这个接口。可以先用通用方法 postAPI 替代。https://help.aliyun.com/document_detail/394478.html#sectiondiv-jp1-eqv-kb4

**Comment by underweather** [comment]
请问FilePutUserTags这个api对应的postApi的路径在哪里找呢？

**Comment by underweather** [comment]
> 目前还没有这个接口。可以先用通用方法 postAPI 替代。https://help.aliyun.com/document_detail/394478.html#sectiondiv-jp1-eqv-kb4
请问FilePutUserTags这个api对应的postApi的路径在哪里找呢？
