### ISSUE TITLE
任务暂停后如何继续上传呢？

### ISSUE THREAD

**Issue by underweather** [aliyun/aliyun-pds-js-sdk#7]
您好，现在遇到的一个问题是任务调用stop方法后如何继续上传。目前的实现流程是：调用stop方法后，在继续上传的方法中调用当前任务的getCheckpoint（）方法获取checkPoint方法，然后直接传给createUploadTask（）方法。但是报了如下错误：
TypeError: Illegal invocation
    at StandardSerialUploadTask.sliceFile (BaseUploader.js:1173:24)
    at StandardSerialUploadTask.upload_sequential (StandardSerialUploader.js:217:22)
    at StandardSerialUploadTask.upload (StandardSerialUploader.js:167:23)
    at StandardSerialUploadTask.run (BaseUploader.js:676:20)
    at async StandardSerialUploadTask.doStart (BaseUploader.js:556:7)
handleError @ BaseUploader.js:287
doStart @ BaseUploader.js:563
await in doStart (async)
start @ BaseUploader.js:548
doUploadFile @ pds.ts:128
restartTask @ index.ts:146
(anonymous) @ pinia.mjs:1359
store.<computed> @ pinia.mjs:917
restartTask @ TransferItemView.vue:142
delTask @ TransferItemView.vue:126
_createElementVNode.onClick._cache.<computed>._cache.<computed> @ TransferItemView.vue:51
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:370
请问是哪里非法引用呢？感谢
或者调用task的stop方法后，如何继续上传当前任务呢？

**Comment by aleelock** [comment]
如果是在浏览器里使用，checkpoint中的 file 必须是HTML File对象，由于浏览器的安全限制，必须由用户选择文件触发。

**Comment by aleelock** [comment]
替换checkpoint里面的file为HTML File，才能传入 createUploadTask()。
