### ISSUE TITLE
前端文件下载

### ISSUE THREAD

**Issue by underweather** [aliyun/aliyun-pds-js-sdk#8]
您好，请问要sdk有封装供纯前端调用的方法可以进行文件批量下载吗？看downloadFile 和 createDownloadTask仅支持 node.js 环境调用

**Comment by aleelock** [comment]
web 端的下载有3种方式，下面分别介绍下。

第一种：listFiles/getFile 返回的文件 IFileItem 里有个 download_url 字段，可以用浏览器直接打开下载。这种方式只能下载单个文件，不能下载多个文件或目录。

第二种：通过钉钉找 "PDS技术支持" 开通服务端打包下载的增值服务，调用 client.pollingArchiveFile() 方法，拿到 url 字段后用浏览器直接打开下载。这种方式可以下载多个文件和目录。

第三种：递归遍历文件列表和目录中的每个文件的 download_url，在前端下载并 zip。这种方式可以下载多个文件和目录，但是占用内存较大，不适合下载较大文件或目录。

Web 端下载，推荐使用第一和第二种结合的方式。单个文件用第一种，多个文件或目录用第二种。
