### ISSUE TITLE
请问如何实现文件转存功能

### ISSUE THREAD

**Issue by underweather** [aliyun/aliyun-pds-js-sdk#9]
请问，jssdk有实现文件转存功能的相关接口吗？使用场景：用户A分享给用户B的文件，用户B可以保存在自己的云盘。请问，有相关的接口可以实现该功能吗？谢谢~

**Comment by aleelock** [comment]
copyFiles方法可以： `await client.copyFiles(items, {to_parent_file_id, to_drive_id})`
